# See https;//taskfile.dev for more information about Taskfile syntax
version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from templates"
    cmds:
      - protoc -I proto proto/sso/sso.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
      - protoc -I proto proto/aliver/aliver.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
  